return {
  kind = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
<<<<<<< HEAD
    Folder = "",
=======
    Folder = "󰉋",
>>>>>>> 14b0878 (upgrade new lunar vim)
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
<<<<<<< HEAD
    Null = "ﳠ",
=======
    Null = "󰟢",
>>>>>>> 14b0878 (upgrade new lunar vim)
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
  git = {
    LineAdded = "",
    LineModified = "",
    LineRemoved = "",
    FileDeleted = "",
    FileIgnored = "◌",
    FileRenamed = "",
    FileStaged = "S",
    FileUnmerged = "",
    FileUnstaged = "",
    FileUntracked = "U",
    Diff = "",
    Repo = "",
    Octoface = "",
    Branch = "",
  },
  ui = {
    ArrowCircleDown = "",
    ArrowCircleLeft = "",
    ArrowCircleRight = "",
    ArrowCircleUp = "",
    BoldArrowDown = "",
    BoldArrowLeft = "",
    BoldArrowRight = "",
    BoldArrowUp = "",
    BoldClose = "",
    BoldDividerLeft = "",
    BoldDividerRight = "",
    BoldLineLeft = "▎",
    BookMark = "",
    BoxChecked = "",
    Bug = "",
    Stacks = "",
    Scopes = "",
<<<<<<< HEAD
    Watches = "",
    DebugConsole = "",
    Calendar = "",
    Check = "",
    ChevronRight = ">",
    ChevronShortDown = "",
    ChevronShortLeft = "",
    ChevronShortRight = "",
    ChevronShortUp = "",
    Circle = "",
    Close = "",
=======
    Watches = "󰂥",
    DebugConsole = "",
    Calendar = "",
    Check = "",
    ChevronRight = "",
    ChevronShortDown = "",
    ChevronShortLeft = "",
    ChevronShortRight = "",
    ChevronShortUp = "",
    Circle = " ",
    Close = "󰅖",
>>>>>>> 14b0878 (upgrade new lunar vim)
    CloudDownload = "",
    Code = "",
    Comment = "",
    Dashboard = "",
    DividerLeft = "",
    DividerRight = "",
    DoubleChevronRight = "»",
    Ellipsis = "",
    EmptyFolder = "",
    EmptyFolderOpen = "",
    File = "",
    FileSymlink = "",
    Files = "",
<<<<<<< HEAD
    FindFile = "",
    FindText = "",
    Fire = "",
    Folder = "",
=======
    FindFile = "󰈞",
    FindText = "󰊄",
    Fire = "",
    Folder = "󰉋",
>>>>>>> 14b0878 (upgrade new lunar vim)
    FolderOpen = "",
    FolderSymlink = "",
    Forward = "",
    Gear = "",
    History = "",
    Lightbulb = "",
    LineLeft = "▏",
    LineMiddle = "│",
    List = "",
    Lock = "",
    NewFile = "",
    Note = "",
    Package = "",
<<<<<<< HEAD
    Pencil = "",
=======
    Pencil = "󰏫",
>>>>>>> 14b0878 (upgrade new lunar vim)
    Plus = "",
    Project = "",
    Search = "",
    SignIn = "",
    SignOut = "",
<<<<<<< HEAD
    Tab = "",
=======
    Tab = "󰌒",
>>>>>>> 14b0878 (upgrade new lunar vim)
    Table = "",
    Target = "󰀘",
    Telescope = "",
    Text = "",
    Tree = "",
<<<<<<< HEAD
    Triangle = "契",
=======
    Triangle = "󰐊",
>>>>>>> 14b0878 (upgrade new lunar vim)
    TriangleShortArrowDown = "",
    TriangleShortArrowLeft = "",
    TriangleShortArrowRight = "",
    TriangleShortArrowUp = "",
  },
  diagnostics = {
    BoldError = "",
    Error = "",
    BoldWarning = "",
    Warning = "",
    BoldInformation = "",
    Information = "",
    BoldQuestion = "",
    Question = "",
    BoldHint = "",
<<<<<<< HEAD
    Hint = "",
=======
    Hint = "󰌶",
>>>>>>> 14b0878 (upgrade new lunar vim)
    Debug = "",
    Trace = "✎",
  },
  misc = {
<<<<<<< HEAD
    Robot = "ﮧ",
=======
    Robot = "󰚩",
>>>>>>> 14b0878 (upgrade new lunar vim)
    Squirrel = "",
    Tag = "",
    Watch = "",
    Smiley = "",
    Package = "",
    CircuitBoard = "",
  },
}
